<li class="menu-header">Main Menu</li>
<li class="{{ Request::is('admin/list-users') || Request::is('admin/create-users') || Request::is('admin/edit-users/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-users') }}"><i class="fas fa-users"></i> <span>Users</span></a></li>
<li class="{{ Request::is('admin/list-category') || Request::is('admin/create-category') || Request::is('admin/edit-category/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-category') }}"><i class="fas fa-icons"></i><span>Category</span></a></li>
<li class="{{ Request::is('admin/list-variation') || Request::is('admin/create-variation') || Request::is('admin/edit-variation/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-variation') }}"><i class="fas fa-object-group"></i><span>Variation</span></a></li>
<li class="{{ Request::is('admin/list-product') || Request::is('admin/create-product') || Request::is('admin/edit-product/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-product') }}"><i class="fas fa-cubes"></i><span>Product</span></a></li>
<li class="{{ Request::is('admin/list-variation-option') ||Request::is('admin/create-variation-option') ||Request::is('admin/edit-variation-option/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-variation-option') }}"><i class="fas fa-object-ungroup"></i><span>Variation Option</span></a></li>
<li class="{{ Request::is('admin/list-merge-varOption') || Request::is('admin/create-merge-varOption') || Request::is('admin/edit-merge-varOption/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-merge-varOption') }}"><i class="fas fa-th large"></i><span>Merge Variation Option</span></a></li>
<li class="{{ Request::is('admin/list-voucher') || Request::is('admin/create-voucher') || Request::is('admin/edit-voucher/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-voucher') }}"><i class="fas fa-money-bill-wave"></i><span>Voucher</span></a></li>
<li class="{{ Request::is('admin/list-banner') || Request::is('admin/create-banner') || Request::is('admin/edit-banner/*') ? 'active' : '' }}"><a class="nav-link" href="{{ url('/admin/list-banner') }}"><i class="fas fa-money-check"></i><span>Banner</span></a></li>
